Frontend/feature/cardcomponent
2110336-SoftwareEngineering2/sec1_InfraTech pull request #15
Opened 2021-02-17 05:14 UTC by chaincoyg

2021-02-17 05:41 UTC, KKCORR requested changes

2021-02-17 05:41 UTC, KKCORR commented on frontend/components/PreferrenceCard.js
> +          <></>
แนะนำว่าแทนที่จะใช้ 
`{click ? <Component /> : <></> }`
ให้ใช้ 
`{click && <Component />}`
แทนดีกว่า

2021-02-17 05:41 UTC, KKCORR commented on frontend/components/PreferrenceCard.js
> +const PreferrenceCard = ({}) => {
ควรทำให้ส่ง รูป, description ของ card นั้นๆ ผ่านทาง prop มาได้

2021-02-17 05:41 UTC, KKCORR commented on frontend/components/PreferrenceCard.js
> +      </div>
ควรเอา image url มาจาก prop

2021-02-17 05:41 UTC, KKCORR commented on frontend/components/PreferrenceCard.js
> +        <img alt="example" src="a.jpg" class="object-contain h-60 w-60 " />
ควรใช้ `<Image />` จาก next/image แทน `<img />`

2021-02-17 05:41 UTC, KKCORR commented on frontend/components/PreferrenceCard.js
> +      </div>
ควรเอา description มาจาก prop

2021-02-17 05:41 UTC, KKCORR commented on frontend/components/PreferrenceCard.js
> +            }}
สามารถใช้ class ของ tailwind แทนได้มั้ย

2021-02-17 05:41 UTC, KKCORR commented on frontend/components/PreferrenceCard.js
> +          <CheckCircleOutlined
ใช้ `<CheckCircleFilled />` แทน `<CheckCircleOutlined />`

2021-02-17 05:41 UTC, KKCORR commented on frontend/components/PreferrenceCard.js
> +      <div className="w-full h-0 text-right items-start relative ">
ทำไม h-0 นะ

2021-02-17 06:09 UTC, WachirapatMT commented on frontend/components/PreferrenceCard.js
> +        <img alt="example" src="a.jpg" class="object-contain h-60 w-60 " />
ใช้ className แทน class

2021-02-17 06:09 UTC, WachirapatMT commented on frontend/components/PreferrenceCard.js
> +};
export default ไว้ด้วยเลย

2021-02-17 06:15 UTC, WachirapatMT commented on frontend/components/PreferrenceCard.js
> +        <span className="text-sm">Strength</span>
span จำเป็นมั้ย ถ้าไม่ก็ย้าย text-sm จาก span ไปที่ div แล้วเอา span ออกเลยก็ได้

2021-02-17 06:22 UTC, WachirapatMT commented on frontend/components/PreferrenceCard.js
> +        <img alt="example" src="a.jpg" class="object-contain h-60 w-60 " />
ถ้าต้องการใช้ mock image url ให้ตั้งชื่อที่มีความหมาย เช่น mockPreferenceCard.png

2021-02-17 06:23 UTC, WachirapatMT commented on frontend/components/PreferrenceCard.js
> +};
เขียนอธิบาย pull request พร้อมแคปรูปหน้าจอหรือ component ด้วยถ้าเป็นไปได้ เพื่อที่คนรีวิวจะได้เห็นภาพมากขึ้น

2021-02-17 06:44 UTC, WachirapatMT requested changes

2021-02-17 06:44 UTC, WachirapatMT commented on frontend/components/PreferrenceCard.js
> +      <img alt={alt} src={url} layout="fill" />
ใช้ `<Image/>`ของ next/image แทน `<img/>`

2021-02-17 08:56 UTC, WachirapatMT requested changes

2021-02-17 08:56 UTC, WachirapatMT commented on frontend/components/PreferrenceCard.js
> +        click ? ' border-blue' : 'border-black-500 '
tailwind black & white color ไม่มี opacity ไม่ต้องเติมเลขหลังชื่อสี

2021-02-17 08:56 UTC, WachirapatMT commented on frontend/components/PreferrenceCard.js
> +      className={`w-60 h-64 flex flex-col justify-center items-between rounded-md border-2 relative ${
ใส่ background ด้วย
![image](https://user-images.githubusercontent.com/46931722/108178895-8d23b680-7137-11eb-8073-a707dc953fe5.png)

2021-02-17 08:56 UTC, WachirapatMT commented on frontend/components/PreferrenceCard.js
> +      <div className=" w-60 h-12 flex flex-row justify-center text-md">
ทำไมใน pr description เหมือนใช้ bold text แต่ใน className กับตอนลองไม่ได้แบบรูปใน pr
![image](https://user-images.githubusercontent.com/46931722/108179078-c3613600-7137-11eb-8fc8-3361e00c0dd0.png)
text ดูตัวเล็กนะ แล้วก็ลองจัด layout ของ card หน่อยเพราะ text ดูลอยสูงกว่าที่ควร

2021-02-17 08:56 UTC, WachirapatMT commented on frontend/components/PreferrenceCard.js
> +      <div className="w-58 h-52 flex flex-col justify-center items-center rounded-md z-0 ">
![image](https://user-images.githubusercontent.com/46931722/108179688-7893ee00-7138-11eb-8153-a6461dbeae60.png)
position by default คือ static ถ้าแบบนี้ใช้ z ได้เหรอ อันนี้ไม่แน่ใจ ไปลองเช็คดู

2021-02-17 09:01 UTC, KKCORR commented
อยากให้ไปดูเรื่อง ทำยังไงให้ card นี้เอาไปใช้ใน Form ของ antd ได้ด้วย
https://ant.design/components/form/#components-form-demo-customized-form-controls

2021-02-17 16:21 UTC, wichadak commented on frontend/components/PreferrenceCard.js
> +      <div className=" w-60 h-12 flex flex-row justify-center text-md">
good good

2021-02-18 13:01 UTC, WachirapatMT commented on frontend/components/PreferrenceCard.js
> +      className={`w-60 h-64 relative flex flex-col justify-center items-between rounded-md border-2 bg-white ${
เพิ่ม padding top นิดนึงจะดี แล้วก็ถ้าเป็นทรงสี่เหลี่ยมจัตุรัสจะดูดีกว่านะ (คหสด.)

2021-02-18 14:23 UTC, chaincoyg commented on frontend/components/PreferrenceCard.js
> +      className={`w-60 h-64 relative flex flex-col justify-center items-between rounded-md border-2 bg-white ${
ตอนแรกคิดว่า จะเอารูปเข้ามาพอดีเป็นจตุรัส

2021-02-19 15:57 UTC, closed without merging