Frontend/feature/register form
2110336-SoftwareEngineering2/sec1_InfraTech pull request #36
Opened 2021-02-22 07:28 UTC by Flumen17

### Short Description
style all steps in the register form.

### Changes
implement real select-role and select-preferences form
style registration form

### Todos
input for upload profile image
responsive for registration form

### Screenshots
![image](https://user-images.githubusercontent.com/46940660/108675812-e0bc4880-7519-11eb-833d-1e3796ddcd50.png)
![image](https://user-images.githubusercontent.com/46940660/108675890-fa5d9000-7519-11eb-9e57-5fdb90ee9f5b.png)
![image](https://user-images.githubusercontent.com/46940660/108675945-0ea18d00-751a-11eb-841e-b035c0e5feda.png)
![image](https://user-images.githubusercontent.com/46940660/108675997-24af4d80-751a-11eb-890d-6eb91afd8ae9.png)

2021-02-22 09:21 UTC, techid2000 requested changes

2021-02-22 09:21 UTC, techid2000 commented on frontend/components/register/FillInformationForm.js
> +          <div className="hidden md:block mt-0 lg:mt-10 mx-8">
เอา `hidden md:block` ออกมั้ย เพราะภาพโปรไฟล์ไม่ควรหายอะถึงแม้จะย่อหน้าจอ

2021-02-22 09:21 UTC, techid2000 commented on frontend/components/register/FillInformationForm.js
> +                  {type: 'date', message: 'Date format is incorrect.'},
ทำไมตรงนี้ต้องมีนะ ไม่ได้ใช้ Date picker อยู่แล้วเหรอ

2021-02-22 09:21 UTC, techid2000 commented on frontend/components/register/FillInformationForm.js
> +                <DatePicker style={{ width: '100%' }} placeholder="Date of birth" format="DD/MM/YYYY" />
ใช้ `className="w-full"` แทนการเขียน styles ได้ปะนะ ไม่มั่นใจ

2021-02-22 09:21 UTC, techid2000 commented on frontend/components/register/FillInformationForm.js
> -            {validator: (_, value) => {
NTH: อยากให้มีการแยก logic ออกมาจาก jsx เพราะโค้ดจะดูรกและอ่านยากไป

2021-02-22 09:21 UTC, techid2000 commented on frontend/components/register/SelectPreferencesForm.js
> +  for(let index=0; index<preferenceOptions.length; index+=2){
NTH: จริงๆ ใช้แค่ `Row` เดียว แล้วให้ `Col span={12}` แล้ววนใส่ไปเลยก็ได้นะ มันจะตัดขึ้นบรรทัดใหม่ให้

2021-02-22 09:21 UTC, techid2000 commented on frontend/components/register/SelectPreferencesForm.js
> +const SelectPreferencesInput = ({ value = [], onChange }) => {
NTH: แยก Component ไปอีกไฟล์ดีมะ

2021-02-22 09:21 UTC, techid2000 commented on frontend/components/register/SelectRoleForm.js
> +const SelectRoleInput = ({ value , onChange }) => {
NTH: แยก Component ไปอีกไฟล์ดีมะ

2021-02-22 09:21 UTC, techid2000 commented on frontend/components/register/SelectRoleForm.js
> +      <SelectionCard flag={value=="trainee"} imageUrl="/trainee.svg" description="Trainee" onClick={() => onChange("trainee")}/>
ควรเปลี่ยน `onChange` เป็น `onClick` หรือเปล่านะ?

2021-02-22 09:24 UTC, Flumen17 commented on frontend/components/register/FillInformationForm.js
> +          <div className="hidden md:block mt-0 lg:mt-10 mx-8">
เอาของอีกอันมาใส่คร่าวๆไว้ รอเชนทำอัพโหลดรูปโปรไฟล์

2021-02-22 09:25 UTC, Flumen17 commented on frontend/components/register/SelectPreferencesForm.js
> +  for(let index=0; index<preferenceOptions.length; index+=2){
มันตัดบรรทัดให้ แต่ตัวพื้นหลังสีขาวมันยืดออกไม่ fit content อะ

2021-02-22 09:26 UTC, Flumen17 commented on frontend/components/register/FillInformationForm.js
> +                  {type: 'date', message: 'Date format is incorrect.'},
@wongtawan-j

2021-02-22 09:27 UTC, Flumen17 commented on frontend/components/register/FillInformationForm.js
> +                <DatePicker style={{ width: '100%' }} placeholder="Date of birth" format="DD/MM/YYYY" />
@wongtawan-j

2021-02-22 09:27 UTC, Flumen17 commented on frontend/components/register/FillInformationForm.js
> -            {validator: (_, value) => {
@wongtawan-j

2021-02-22 09:36 UTC, WachirapatMT requested changes
คราวหน้า pr แยกกว่านี้หน่อยก็ดี แบบค่อยๆมาทีละ step ก็ได้ แล้วก็ใช้ prettier format ก่อน pr ด้วย

2021-02-22 09:36 UTC, WachirapatMT commented on frontend/components/register/SelectRoleForm.js
> +      <SelectionCard flag={value=="trainee"} imageUrl="/trainee.svg" description="Trainee" onClick={() => onChange("trainee")}/>
ทำไมอันนึงเรียก onClick แต่อีกอันเรียก onChange

2021-02-22 09:36 UTC, WachirapatMT commented on frontend/components/register/SelectRoleForm.js
>          initialValues={getState('select-role', { role: 'trainer' })}
ทุกจุดที่เป็น role value ให้ใช้ค่าจาก config/UserType.config.js

2021-02-22 09:37 UTC, Flumen17 commented on frontend/components/register/SelectPreferencesForm.js
> +  for(let index=0; index<preferenceOptions.length; index+=2){
![image](https://user-images.githubusercontent.com/46940660/108689874-3699ec00-752c-11eb-877b-bf7de85303eb.png)

2021-02-22 17:34 UTC, wongtawan-j commented on frontend/components/register/FillInformationForm.js
> +                  {type: 'date', message: 'Date format is incorrect.'},
ตอนแรกเช็คเผื่อไว้อะ ถถถถ ไปเอาออกละ

2021-02-22 17:39 UTC, wongtawan-j commented on frontend/components/SelectionCard.js
> +const SelectionCard = ({ flag, onClick, imageUrl, description}) => {
อันนี้เหมือน mark ไปเปลี่ยนละ ผม resolve เลยนะ

2021-02-23 02:31 UTC, WachirapatMT commented on frontend/package.json
> +    "dotenv": "^8.2.0",
ลง cookie กับ dotenv ทำไม

2021-02-23 02:31 UTC, WachirapatMT commented on frontend/components/CustomUpload.js
> +//   };
ตรง comment ต้องเก็บไว้มั้ย

2021-02-23 02:31 UTC, WachirapatMT commented on frontend/components/CustomUpload.js
> +      console.log(imageUrl);
console.log  ถ้าจะเก็บไว้ก่อนก็ comment หน่อย ไม่งั้นเวลาคนอื่นมาลองรันมันจะพ่นอะไรออกมาเยอะไป

2021-02-23 03:35 UTC, KKCORR requested changes

2021-02-23 03:35 UTC, KKCORR commented on frontend/components/CustomUpload.js
> +import React, { Component, useState } from 'react';
ควรเอา import `Component` เพราะไม่ได้ใช้

2021-02-23 03:35 UTC, KKCORR commented on frontend/components/CustomUpload.js
> +import fire from '../config/firebase';
ควรเอา import `fire` ออกเพราะไม่ได้ใช้

2021-02-23 03:35 UTC, KKCORR commented on frontend/components/CustomUpload.js
> +  const getBase64 = (file) => {
ถ้า `getBase64` ไม่ได้ใช้ตัวแปรข้างใน `CustomUpload` ควรแยกออกไปข้างนอก จะได้ไม่ต้องประกาศทุกรอบที่ rerender

2021-02-23 03:35 UTC, KKCORR commented on frontend/components/CustomUpload.js
> +    const isLt5M = file.size / 1024 / 1024 < 5;
อาจจะใช้ค่าจาก `.env` เพื่อกำหนด `MAXIMUM_IMAGE_FILE_SIZE_MB`

2021-02-23 03:35 UTC, KKCORR commented on frontend/components/CustomUpload.js
> +        <Image src={imageUrl ? imageUrl : "/avatar.svg"} width={240} height={240} layout="fixed" className="rounded-full align-middle"/>
`imageUrl ? imageUrl : "/avatar.svg"` ใช้เป็น `imageUrl ||  "/avatar.svg"` ดีกว่า

2021-02-23 03:35 UTC, KKCORR commented on frontend/components/CustomUpload.js
> +          loading ? <LoadingOutlined className="absolute top-1/2 left-1/2 -mt-2 -ml-2"/> : null
ใช้เป็น `loading && <LoadingOutlined className="absolute top-1/2 left-1/2 -mt-2 -ml-2"/>` ดีกว่า

2021-02-23 03:35 UTC, KKCORR commented on frontend/config/firebase.js
> +export default fire;
แทนที่จะเป็น 
```
const fire = firebase;
export default fire;
```
ใช้เป็น
```
const storage = firebase.storage();
export { storage, firebase as default };
```
น่าจะดีกว่า

2021-02-23 03:35 UTC, KKCORR commented on frontend/config/firebase.js
> +  if (!/already exists/.test(err.message)) {
@chaincoyg ตรงนี้หมายความว่าไรอะ เอามาจากตรงไหนนะ

2021-02-23 05:00 UTC, KKCORR commented on frontend/config/firebase.js
> +export default fire;
อ้างอิงจากตรงนี้ (https://dev.to/itnext/how-to-do-image-upload-with-firebase-in-react-cpj)
![image](https://user-images.githubusercontent.com/46840981/108803977-a82a7680-75ce-11eb-840e-b68a106c3234.png)

2021-02-23 07:56 UTC, KKCORR commented on frontend/components/CustomUpload.js
> +    const isLt5M = file.size / 1024 / 1024 < 5;
Note: เอาไว้ pr หน้าก็ได้

2021-02-23 08:06 UTC, KKCORR commented on frontend/config/firebase.js
> +export default fire;
Note: เอาไว้ pr หน้าก็ได้

2021-02-23 13:00 UTC, KKCORR approved these changes

2021-02-23 13:03 UTC, techid2000 approved these changes

2021-02-23 13:04 UTC, merged